# Generated by Django 4.0.5 on 2022-06-04 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Тип товара')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Название товара')),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.FileField(upload_to='uploads/')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.address')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.type')),
            ],
        ),
    ]
