# Generated by Django 4.0.5 on 2022-06-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='attachment',
            field=models.FileField(upload_to='uploads/', verbose_name='Вложение'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AlterModelTable(
            name='delivery',
            table='delivery',
        ),
    ]
