# Generated by Django 4.0.5 on 2022-06-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_delivery_attachment_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='type',
            table='type',
        ),
    ]
