# Generated by Django 4.0.5 on 2022-06-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_address_table_alter_delivery_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='delivery',
            table='delivery',
        ),
        migrations.AlterModelTable(
            name='type',
            table='type',
        ),
    ]
