# Generated by Django 4.0.5 on 2022-06-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_address_table_alter_delivery_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
    ]
