# Generated by Django 4.0.5 on 2022-06-06 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_delivery_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='delivery.address'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Вложение'),
        ),
        migrations.AlterModelTable(
            name='address',
            table=None,
        ),
        migrations.AlterModelTable(
            name='delivery',
            table=None,
        ),
    ]
