# Generated by Django 4.0.5 on 2022-06-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_address_address_alter_delivery_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='name',
        ),
    ]
